### ISSUE TITLE
skip waiting page

### ISSUE THREAD

**Issue by akosglue** [wl-online-payments-direct/plugin-magento-core#8]
Hi, 

Is it possible to skip the waiting page?
So that I don't end up on the magento waiting page but I stay on the ingeno payment page until the waiting is done.
Only redirect back to magento to the success page.

Thanks

**Comment by mathieubroekaert** [comment]
Hello @akosglue 

For the moment it's not possible to skip this page. The waiting page on Magento manages a combination of webhooks handling and get calls in order to make sure the order is correctly created, hence it would be complicated to skip it without risking to impact the order creation flow.

However, rest assured that the display of this page will be very limited, as the customer will be redirected to an order confirmation page as soon as the order will be successfully created. Note that if the order is created even before this page is reached it could even be completely skipped !

**Comment by akosglue** [comment]
Hi, thanks, I understand.
However, what happens if the user won't wait for the redirect from the payment page to the shop (waiting page)?
So, the user pays, gets the message that the payment is accepted and just closes the tab/window. The user never sees the actual waiting page (or the shop) again.

Can it happen that the order is never created in magento and it just stays in the quotes table with reserved id?
This seems to be the case in our shop.

**Comment by mathieubroekaert** [comment]
Hello,
Let me describe the process in a bit more details : 
once a customer has placed an order, a webhook is being triggered from the Worldline platform: 

- If the webhook arrives immediately, the order is immediately created and the customer is redirected to an “Order confirmation” page
- If the webhook is not immediately integrated on Magento, the customer is redirected to a “Waiting” page, where we will still listen to webhooks for 15 seconds. As soon as the webhook arrives, the customer is redirected to an “Order confirmation” page.
- If the webhook doesn’t arrive within 15 seconds, two process take over: 

1. A first get call is triggered in order to fetch the transaction status directly from Worldline
2. If this get call doesn’t result into a final result, a cronjob takes over and will trigger get calls at regular intervals in order to update the order accordingly.

So in the use-case you describe, if the consumer closes the browser, we will still wait for a webhook to come to create the order, and if it doesn't arrive within 1 minute (default value, editable) a cron job will take over and perform a GET call to create it.
And in case the payment is not processed at all, the inventory will be released after 3 hours (default value, editable).

In order to configure those settings, just browse to **Worldline Online Payments > Dynamic order status synchronization** and edit the following values : 
- Fallback timeout : determines after how many minutes the cron takes overs
- Fallback timeout limit : determines for how long the cron will run, and after how long the inventory will be released.

In your case, are you using the latest version of the plugin ? If not, could you upgrade to the 2.5.0 ? There could also be interactions with other plugins, so it could be an option to try and deactivate the rest of them and see if it improves the behavior.

**Comment by WorldlineMagentoTeam** [comment]
Hello @akosglue.
Please, make sure that webhooks are set up correctly and cron is running.
Thank you! Let us know if you need any support. For now, the original issue will be closed.
